function settings_ideal = define_ideal_settings()
% Defines the baseline settings that I'm using for my Zimmer models
settings_ideal = struct(...
    'to_subtract_mean',false,...
    'to_subtract_baselines',false,...
    'to_subtract_mean_sparse',false,...
    'to_subtract_mean_global',false,...
    'add_constant_signal',false,...
    'use_deriv',false,...
    'augment_data', 0,...
    ...'filter_window_global', 0,...
    'filter_window_dat', 1,...
    'dmd_mode','func_DMDc',...
    'global_signal_subset', {{'all'}},...
    ...'autocorrelation_noise_threshold', 0.3,...
    'lambda_sparse',0);
settings_ideal.global_signal_mode = 'ID_binary_transitions';
end

